angular.module("module").constant("serverUrl", "http://localhost:9408/");
angular.module("module").constant("pages", {
    // common: ["notifications", "home"],
    Admin: ["",
        "home",
        "index",
        "profile",
        "forgetPassword",
        "recover",
        "login",
        "test",
        "unauthorized",
        "notifications",
        "parent",
        "child",
        "updatechild",
        "createparent",
        "updateparent",
        "createchild",
        "contacts",
        "reportView",
        "therapistReport",
        "parentReport",
        "invoiceReport",
        "invoicedownload",
        "homeFundInvoice",
        "generalInvoice",
        "therapistReportView",
        "biMonthReport",
        "endMonthReport",
        "therapist",
        "finalMonthReport", "therapistDetails",
        "session", "scheduleAll", "sessiondetails", "updatesession", "assigntogroup",
        "newSession", "sessionFinshing", "updateTherapist", "therapistTask",
        "createTask", "createTherapist", "rateTherapist", "editTherapist",
        "answercomplaint", "childrenSession", "childschedule",
        "Allcomplaint", "createContact", "updateContact", "parentemail",
        "createparentemail", "updateparentemail", "addRate", "rate", "updateTask"

    ],
    Parent: ["",
        "home", "index", "profile", "forgetPassword", "recover", "login", "test", "unauthorized",
        "home", "notifications", "childschedule", "parentprofile", "createChildAvailability", "childAvailability", "login", "complaint", "createcomplaint", "complaintdetails"
    ],
    Therapist: ["",
        "home", "profile", "forgetPassword", "recover", "login", "test", "unauthorized", "index", "therapistschedule",
        "home", "notifications", "login", "createTherapistAvailability", "therapistAvailability", "complaint", "createcomplaint", "complaintdetails"
    ]
});